# Generated by Django 3.0.5 on 2020-04-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200404_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
